version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - network
    restart: always

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - network
    restart: always

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - network
    restart: always

volumes:
  data:

networks:
  network:
