version: '3'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - network
    restart: always

volumes:
  data:

networks:
  network:
