version: '3'

services:
  postgres:
    container_name: transcendence-postgres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - transcendence
    restart: always

  backend:
    container_name: transcendence-backend
    image: transcendence-backend
    build:
      context: ./backend
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - transcendence
    restart: always

  frontend:
    container_name: transcendence-frontend
    image: transcendence-frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - transcendence
    restart: always

networks:
  transcendence:
    name: transcendence

volumes:
  database:
  backend:
  backend_node_modules:
  frontend:
  frontend_node_modules:
