version: "3"

services:
  postgres:
    container_name: transcendence-postgres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - transcendence
    restart: always

  backend:
    container_name: transcendence-backend
    image: transcendence-backend
    build:
      context: ./backend
      dockerfile: ./prod.Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 3000:3000
      - 5555:5555
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules
    networks:
      - transcendence
    restart: always

  frontend:
    container_name: transcendence-frontend
    image: transcendence-frontend
    build:
      context: ./frontend
      dockerfile: ./prod.Dockerfile
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - 80:80
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    networks:
      - transcendence
    restart: always

networks:
  transcendence:
    name: transcendence

volumes:
  database:
