export const channelsData = [
  { id: 1, name: "Creators Area ", status: "Public" },
  { id: 2, name: "Project Lumos", status: "Password" },
  { id: 3, name: "Les momos", status: "Private" },
  { id: 4, name: "fluchten's channel", status: "Private" },
  { id: 5, name: "TechTalks", status: "Public" },
  { id: 6, name: "GameFreaks", status: "Public" },
  { id: 7, name: "CodeMasters", status: "Private" },
  { id: 8, name: "TravelEnthusiasts", status: "Public" },
  { id: 9, name: "FoodiesUnite", status: "Private" },
  { id: 10, name: "BookwormsCorner", status: "Password" },
  { id: 11, name: "MusicMania", status: "Public" },
  { id: 12, name: "FitnessFiesta", status: "Private" },
  { id: 13, name: "TechInnovation", status: "Public" },
  { id: 14, name: "MovieBuffZone", status: "Password" },
  { id: 15, name: "ArtistsCollective", status: "Public" },
  { id: 16, name: "ScienceExplorers", status: "Public" },
  { id: 17, name: "GamingGuild", status: "Private" },
  { id: 18, name: "PetLoversParadise", status: "Public" },
  { id: 19, name: "WellnessWave", status: "Password" },
  { id: 20, name: "PhotographyPassion", status: "Public" },
];
